export const Paths = {
  Route_Home: "/",
  Route_Celebrities: "/celebrities",
  Route_Celebrity_Detail: "/celebrities/:slug",
  Route_Movies: "/movies",
  Route_Movie_Detail: "/movies/:slug",
  Route_Login: "/login",
  Route_Register: "/register",
  Route_Register_Crew: "/register-crew",
  Route_Aboutus: "/aboutus",
  Route_Forogot_Password: "/forgotpassword",
  Route_Verify_Email: "/verifyemail",

  //protected routes ie. admin/dashboard
  Route_Admin: "/admin",
  Route_Admin_Dashboard: "/admin/dashboard",
  Route_Admin_Movie: "/admin/movies",
  Route_Admin_Movie_Add: "/admin/movies/create",
  Route_Admin_Crew: "/admin/crew",
  Route_Admin_Crew_Add: "/admin/crew/create",
  Route_Admin_Role: "/admin/role",
  Route_Admin_Role_Add: "/admin/role/create",
  Route_Admin_ProductionHouse: "/admin/production-house",
  Route_Admin_ProductionHouse_Add: "/admin/production-house/create",
  Route_Admin_Scholarship: "/admin/scholarship",
  Route_Admin_Scholarship_Bachelors: "/admin/scholarship/bachelors",
  Route_Admin_Scholarship_Masters: "/admin/scholarship/masters",
  Route_Admin_Theatre: "/admin/theatre",
  Route_Admin_Theatre_Add: "/admin/theatre/create",
  Route_Admin_Awards: "/admin/awards",
  Route_Admin_Awards_Add: "/admin/awards/create",
};
